server:
  host: 192.168.111.143
  mode: debug
  port: 8000
logger:
  path: ./logs
  level: info
mysql:
  host: 192.168.111.143
  port: 3306
  db: sxp-server
  username: root
  password: 123456
redis:
  addr: 192.168.111.143:6379
  password: ""
jwt:
  secret: sxp-server
  #多少秒过期
  timeout: 18000
grpc:
  addr: 192.168.111.40:9011
  retry: 3
  timeout: 15
jaeger:
  addr: 192.168.111.143:6831
Kafka:
  brokers: [192.168.111.143:9092]
  producerTimeOut: 100000
  consumerTimeOut: 1000
  async: true
  ack: -1
  retryCount: 3
